# Generated by Django 5.2.7 on 2025-10-31 17:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_scanconfiguration_alter_globalstats_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserExtensionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('browser_info', models.JSONField(default=dict)),
                ('extension_version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeepScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scan_intensity', models.CharField(choices=[('quick', 'Quick Scan'), ('standard', 'Standard Audit'), ('comprehensive', 'Deep Audit')], default='standard', max_length=20)),
                ('recorded_actions', models.JSONField(default=list)),
                ('session_data', models.JSONField(default=dict)),
                ('vulnerability_focus', models.JSONField(default=list)),
                ('advanced_options', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('configuring', 'Configuring'), ('recording', 'Recording Session'), ('ready', 'Ready to Scan'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='configuring', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('current_module', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording_started_at', models.DateTimeField(blank=True, null=True)),
                ('recording_completed_at', models.DateTimeField(blank=True, null=True)),
                ('scan_started_at', models.DateTimeField(blank=True, null=True)),
                ('scan_completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_vulnerabilities', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('scan_duration', models.FloatField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_scans', to='base.scantarget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_scan_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeepScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField()),
                ('technical_summary', models.JSONField(default=dict)),
                ('risk_metrics', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(default=dict)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='deepscan.deepscansession')),
            ],
        ),
        migrations.CreateModel(
            name='RecordedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('navigation', 'Navigation'), ('click', 'Click'), ('input', 'Input'), ('submit', 'Submit'), ('scroll', 'Scroll'), ('hover', 'Hover'), ('keypress', 'Key Press')], max_length=20)),
                ('target_element', models.CharField(max_length=1000)),
                ('target_selector', models.CharField(blank=True, max_length=1000)),
                ('value', models.TextField(blank=True)),
                ('url', models.URLField(max_length=2000)),
                ('timestamp', models.FloatField()),
                ('screenshot_data', models.TextField(blank=True)),
                ('dom_snapshot', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='deepscan.deepscansession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScanModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('module_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('findings_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='deepscan.deepscansession')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='DeepScanFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=10)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('parameter', models.CharField(blank=True, max_length=500)),
                ('payload', models.TextField(blank=True)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('evidence', models.TextField(blank=True)),
                ('recommendation', models.TextField()),
                ('remediation_complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='deepscan.deepscansession')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_findings', to='deepscan.scanmodule')),
            ],
            options={
                'ordering': ['-cvss_score', '-detected_at'],
            },
        ),
    ]
