# Generated by Django 5.2.7 on 2025-11-14 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepscan', '0002_alter_browserextensionsession_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepscansession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deep_scan_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
