# Generated by Django 5.2.7 on 2025-11-14 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_scanconfiguration_alter_globalstats_options_and_more'),
        ('deepscan', '0003_alter_deepscansession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepscansession',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deep_scans', to='base.scantarget'),
        ),
    ]
