# Generated by Django 5.2.7 on 2025-10-21 23:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scans', models.IntegerField(default=0)),
                ('threats_neutralized', models.IntegerField(default=0)),
                ('active_threats', models.IntegerField(default=0)),
                ('avg_scan_time', models.FloatField(default=0)),
                ('accuracy_rate', models.FloatField(default=99.9)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Global Stats',
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threat_type', models.CharField(choices=[('xss', 'XSS Attack'), ('sqli', 'SQL Injection'), ('rce', 'Remote Code Execution'), ('ddos', 'DDoS Attack'), ('phishing', 'Phishing Attempt'), ('malware', 'Malware Distribution'), ('botnet', 'Botnet Activity')], max_length=50)),
                ('target', models.CharField(max_length=500)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=20)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('scan_type', models.CharField(choices=[('quick', 'Quick Scan'), ('deep', 'Deep Scan'), ('full', 'Full Scan')], default='quick', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('total_vulnerabilities', models.IntegerField(default=0)),
                ('scan_duration', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.scantarget')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('vulnerability_type', models.CharField(choices=[('xss', 'Cross-Site Scripting (XSS)'), ('sqli', 'SQL Injection'), ('rce', 'Remote Code Execution'), ('csrf', 'Cross-Site Request Forgery'), ('lfi', 'Local File Inclusion'), ('xxe', 'XML External Entity'), ('ssrf', 'Server-Side Request Forgery'), ('idor', 'Insecure Direct Object Reference'), ('auth', 'Authentication Bypass'), ('config', 'Security Misconfiguration')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True)),
                ('recommendation', models.TextField()),
                ('fix_time', models.CharField(default='30 minutes', max_length=50)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='base.scanresult')),
            ],
            options={
                'verbose_name_plural': 'Vulnerabilities',
            },
        ),
    ]
