# Generated by Django 5.2.7 on 2025-10-31 00:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_depth', models.IntegerField(default=3)),
                ('timeout', models.IntegerField(default=300)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('excluded_paths', models.JSONField(default=list)),
                ('authentication_required', models.BooleanField(default=False)),
                ('auth_credentials', models.JSONField(default=dict)),
                ('custom_headers', models.JSONField(default=dict)),
                ('scan_schedule', models.JSONField(default=dict)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('notification_channels', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='globalstats',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterModelOptions(
            name='scantarget',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='threatintelligence',
            options={'ordering': ['-detected_at']},
        ),
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'ordering': ['-cvss_score']},
        ),
        migrations.RenameField(
            model_name='globalstats',
            old_name='avg_scan_time',
            new_name='average_scan_duration',
        ),
        migrations.RenameField(
            model_name='globalstats',
            old_name='active_threats',
            new_name='high_risk_scans',
        ),
        migrations.RenameField(
            model_name='globalstats',
            old_name='threats_neutralized',
            new_name='total_vulnerabilities_found',
        ),
        migrations.RemoveField(
            model_name='globalstats',
            name='accuracy_rate',
        ),
        migrations.RemoveField(
            model_name='threatintelligence',
            name='country',
        ),
        migrations.RemoveField(
            model_name='threatintelligence',
            name='source_ip',
        ),
        migrations.RemoveField(
            model_name='threatintelligence',
            name='target',
        ),
        migrations.RemoveField(
            model_name='threatintelligence',
            name='threat_type',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='detected_at',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='fix_time',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='vulnerability_type',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='current_activity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scantarget',
            name='compliance_requirements',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scantarget',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scantarget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scantarget',
            name='last_scan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scantarget',
            name='monitoring_interval',
            field=models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='scantarget',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scantarget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='threatintelligence',
            name='confidence_score',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='threatintelligence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='threatintelligence',
            name='indicators',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='threatintelligence',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threatintelligence',
            name='threat_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='threatintelligence',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threatintelligence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cve_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='is_false_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vulnerabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='risk_score',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='base.scantarget'),
        ),
        migrations.AlterField(
            model_name='scantarget',
            name='scan_type',
            field=models.CharField(choices=[('full', 'Full Scan'), ('quick', 'Quick Scan'), ('compliance', 'Compliance Scan'), ('continuous', 'Continuous Monitoring')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='scantarget',
            name='url',
            field=models.URLField(max_length=2048, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='scantarget',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='threatintelligence',
            name='detected_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='threatintelligence',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='cvss_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='evidence',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['target', 'status'], name='base_scanre_target__f46169_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['started_at'], name='base_scanre_started_ba450f_idx'),
        ),
        migrations.AddIndex(
            model_name='scantarget',
            index=models.Index(fields=['user', 'is_active'], name='base_scanta_user_id_247fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='scantarget',
            index=models.Index(fields=['url'], name='base_scanta_url_f37ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='threatintelligence',
            index=models.Index(fields=['threat_id'], name='base_threat_threat__9be973_idx'),
        ),
        migrations.AddIndex(
            model_name='threatintelligence',
            index=models.Index(fields=['severity', 'is_active'], name='base_threat_severit_e0cad8_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['scan_result', 'severity'], name='base_vulner_scan_re_63bf7b_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['cvss_score'], name='base_vulner_cvss_sc_f0ed0c_idx'),
        ),
        migrations.AddField(
            model_name='scanconfiguration',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='base.scantarget'),
        ),
    ]
